# Generated by Django 4.2.1 on 2023-06-06 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FlightsApi', '0002_alter_user_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='seats',
            new_name='seat_count',
        ),
    ]
