# Generated by Django 4.2.1 on 2023-06-08 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FlightsApi', '0003_rename_seats_ticket_seat_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airlinecompany',
            options={'verbose_name': 'Airline Company', 'verbose_name_plural': 'Airline Companies'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_role',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
