services:
  db:
    image: mysql:latest
    env_file: ./.env
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "--password=$$MYSQL_ROOT_PASSWORD"]
      interval: 3s
      timeout: 3s
      retries: 15
      start_period: 20s
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # image: sivgiv/flight-project-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - backend_data:/app/exposed/
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file: ./.env
volumes:
  db_data:
  backend_data: