version: "3"

services:
  db:
    image: mysql:latest
    env_file: ./.env
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      start_period: 15s
      interval: 3s
      timeout: 3s
      retries: 15
  web:
    image: sivgiv/flightproject:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file: ./.env
volumes:
  db_data: