# Generated by Django 4.2.1 on 2023-08-05 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FlightsApi', '0006_remove_customer_credit_card_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='is_canceled',
            new_name='is_cancelled',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='is_canceled',
            new_name='is_cancelled',
        ),
    ]
